#!/bin/bash

cd ~

./setup-ubuntu-base

sudo apt-get purge -y rhythmbox
sudo apt-get purge -y ubuntu-web-launchers
sudo apt-get purge -y libreoffice-common libreoffice-core
sudo apt-get purge -y rhythmbox
sudo apt-get purge -y cheese

sudo apt-get purge -y thunderbird
sudo apt-get purge -y remmina

sudo apt-get purge -y aisleriot gnome-sudoku libgnome-games-support-common gnome-mahjongg

sudo apt-get autoremove

install/electrum
install/myetherwallet
install/iotawallet

install/gparted
install/nemo

install/trezord
