#!/bin/bash

sudo echo "Installing..." || exit 1

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install wget curl -y

[ -e ~/.install/setup-base ] && exit

install() {
install/$1 | while read line; do echo "[$1] $line"; done
}

install nodejs
install python
install java
install git

echo "#### Installing cryptsetup (needed for LUKS) ####"
sudo apt-get install cryptsetup -y


echo "#### Installing vim ####"
sudo apt-get install vim -y


mkdir -p ~/.install && touch ~/.install/setup-base
