#!/bin/bash

prepend() {
    while read line; do echo "[$1] $line"; done
}

install() {
    install/$1 | prepend $1
}

install-apt() {
    sudo apt-get install $1 -y | prepend "apt:$1"
}

sudo echo "Installing..." || exit 1

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install wget curl -y

[ -e ~/.install/setup-base ] && exit

install nodejs
install python
install java
install git

echo "#### Installing cryptsetup (needed for LUKS) ####"
install-apt cryptsetup


echo "#### Installing vim ####"
install-apt vim

install-apt htop
install-apt iotop

install-apt dirmngr

mkdir -p ~/.install && touch ~/.install/setup-base
