#!/bin/bash

./setup-ubuntu-base

prepend() {
    while read line; do echo "[$1] $line"; done
}

install() {
    install/$1 | prepend $1
}

install-apt() {
    sudo apt-get install $1 -y | prepend "apt:$1"
}
# install compartamentalized stuff

install docker
install atom
install discord
install electrum
install gparted
install chromium
install qbittorrent
install duplicity
install sqlitebrowser
install nemo
install trezord
install vscode
install anki
install sacred
#install keepassx

# install random apt stuff
install-apt keepassxc
install-apt neofetch
install-apt simplescreenrecorder

# set global shortcut to ctrl+alt+a
echo "Patching keepassxc config"
patch ~/.config/keepassxc/keepassxc.ini patches/keepass.patch

echo "#### Installing MySQL Workbench ####"
install-apt mysql-workbench

# install snaps
sudo snap install gimp
sudo snap install --classic eclipse

(
    # printscreen keybind deps
    sudo apt-get install exiftool xclip -y
    bash mk_bindings.sh
) | prepend 'keybinds'

bash mk_startup.sh | prepend 'startup'

# install zh & ja
(
    sudo apt-get install ibus-sunpinyin -y
    sudo apt-get install ibus-anthy -y
    sudo apt-get install ibus-clutter ibus-gtk ibus-gtk3 ibus-qt4 -y
    ibus restart
) | prepend 'lang'

echo "#### Removing unity-webapps-common ####"
sudo apt-get remove unity-webapps-common -y

echo "#### Setting favorite apps ####"
dconf write "/org/gnome/shell/favorite-apps" "['firefox.desktop', 'nemo.desktop', 'org.gnome.Terminal.desktop', 'atom.desktop']"

echo 'PATH=$PATH:~/.local/bin:~/bin' >> ~/.bashrc

echo "Patching nosplash"
sudo patch /etc/default/grub -i patches/nosplash.patchpatch ~/.config/keepassxc/keepassxc.ini keepass.patch
sudo update-grub

echo "Installing aliases"
cp aliases ~/aliases
echo ". ~/aliases" >> ~/.bashrc
