#!/bin/bash

[ -e ~/.install/anki ] && exit

wget https://apps.ankiweb.net/downloads/current/anki-2.1.8-linux-amd64.tar.bz2
tar xjf anki-2.1.8-linux-amd64.tar.bz2
cd anki-2.1.8-linux-amd64
sudo make install
cd ..
rm -rf anki-2.1.8-linux-amd64

mkdir -p ~/.install && touch ~/.install/anki
