#!/bin/bash

[ -e ~/.install/atom ] && exit

echo "######### Installing atom #########"
wget https://atom.io/download/deb -O atom.deb
sudo dpkg -i atom.deb
echo "Expected error--don't panic!"
sudo apt-get --fix-broken install -y
sudo apt-get update && sudo apt-get upgrade -y
sudo dpkg --configure -a
sudo apt-get install -f

sudo dpkg -i atom.deb

rm atom.deb
echo "######### Installing atom package dependencies #########"

pip3 install autopep8 --user

pip3 install python-language-server --user
pip3 install pyls-isort --user
pip3 install pycodestyle --user

mkdir -p ~/.install && touch ~/.install/atom
