#!/bin/bash

[ -e ~/.install/discord ] && exit

echo "######### Installing discord #########"
wget -O discord.deb "https://discordapp.com/api/download?platform=linux&format=deb"
sudo dpkg -i discord.deb
echo "Expected error, don't panic!"
sudo apt-get -fy install
rm discord.deb

mkdir -p ~/.install && touch ~/.install/discord
