#!/bin/bash

[ -e ~/.install/docker ] && exit

echo "#### Installing docker ####"
sudo apt-get remove docker docker-engine docker.io -y
sudo apt-get install  apt-transport-https ca-certificates curl software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
echo "#### Docker key ####"
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get install docker-ce -y

mkdir -p ~/.install && touch ~/.install/docker
