#!/bin/bash

[ -e ~/.install/duplicity ] && exit

echo "#### Installing duplicity ####"

sudo apt-get install -y duplicity
sudo apt-get install --reinstall python-gi -y
sudo apt-get install python3-pyside -y

mkdir -p ~/.install && touch ~/.install/duplicity
