#!/bin/bash

[ -e ~/.install/git ] && exit

echo "######### Installing git #########"

sudo apt-get install git git-gui gitg -y
git config --global core.editor "vim"

mkdir -p ~/.install && touch ~/.install/git
