#!/bin/bash

[ -e ~/.install/java ] && exit

echo "######### Installing Oracle JDK #########"

# automate license
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

sudo apt-get install dirmngr -y

sudo add-apt-repository ppa:linuxuprising/java

# install oracle jdk
sudo apt-get update
sudo apt-get install oracle-java10-installer curl wget jq -y
sudo apt-get install oracle-java10-set-default -y

echo "Setting default java"
sudo sh -c 'echo JAVA_HOME="/usr/lib/jvm/java-8-oracle" >> /etc/environment'
source /etc/environment

mkdir -p ~/.install && touch ~/.install/java
