#!/bin/bash

[ -e ~/.install/keepassx ] && exit

./git

origdir=$PWD

echo "######### Installing KeePassX #########"

mkdir -p /tmp/keepassx
cd /tmp/keepassx

# install dependencies
sudo apt-get install build-essential cmake qtbase5-dev libqt5x11extras5-dev qttools5-dev qttools5-dev-tools libgcrypt20-dev zlib1g-dev libxi-dev libxtst-dev -y
sudo apt-get install qt-sdk -y

git clone https://github.com/keepassx/keepassx
cd keepassx
git checkout 2.0.3

mkdir build
cd build
cmake ..
make

sudo make install

mkdir -p ~/.install && touch ~/.install/keepassx
cd $origdir
