#!/bin/bash

[ -e ~/.install/nodejs ] && exit

echo "######### Installing nodejs #########"

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash

# refresh shell
. ~/.profile
. ~/.bashrc
. ~/.bash_profile

nvm install node

mkdir -p ~/.install && touch ~/.install/nodejs
