#!/bin/bash

[ -e ~/.install/nodejs ] && exit

echo "######### Installing nodejs #########"

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

mkdir -p ~/.install && touch ~/.install/nodejs
