#!/bin/bash

[ -e ~/.install/nodejs ] && exit

echo "######### Installing nodejs #########"

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash

# refresh shell
. ~/.profile
. ~/.bashrc
. ~/.bash_profile

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm install node || exit 1

mkdir -p ~/.install && touch ~/.install/nodejs
