#!/bin/bash

[ -e ~/.install/python ] && exit

echo "######### Installing python #########"

sudo apt-get install -y software-properties-common build-essential python3 python3-distutils python3-testresources libpython3-dev || exit 1
sudo apt-get remove -y python-pip python3-pip || exit 1
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
sudo python3 get-pip.py || exit 1
rm get-pip.py

#pip install -U pip || exit 1
#pip3 install -U pip || exit 1

pip install virtualenv --user || exit 1
pip3 install virtualenv --user || exit 1
pip3 install --user pipenv || exit 1

# needed for matplotlib
sudo apt-get install libpng-dev libfreetype6-dev python3-tk -y || exit 1

# lmxl
sudo apt-get install libxml2-dev libxslt-dev -y

# common pkgs
python3 -m pip install autopep8 jedi matplotlib pillow pyuserinput --user

# ml pkgs
python3 -m pip install jupyter tensorflow torch torchvision gym pandas scipy --user

mkdir -p ~/.install && touch ~/.install/python
