#!/bin/bash

[ -e ~/.install/qbittorrent ] && exit

echo "######### Installing qBitTorrent #########"

sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable -y
sudo apt-get update
sudo apt-get install qbittorrent -y

mkdir -p ~/.install && touch ~/.install/qbittorrent
