#!/bin/bash

[ -e ~/.install/sacred ] && exit

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
sudo apt update
sudo apt install -y mongodb-org

sudo systemctl start mongod.service
sudo systemctl enable mongod.service

pip3 install sacred --user
pip3 install pymongo --user

npm install -g omniboard

mkdir -p ~/.install && touch ~/.install/sacred
