#!/bin/bash

[ -e ~/.install/sqlitebrowser ] && exit

echo "######### Installing SQLite Browser & setting as default #########"

sudo add-apt-repository -y ppa:linuxgndu/sqlitebrowser
sudo apt-get update
sudo apt-get install sqlitebrowser -y

mkdir -p ~/.install && touch ~/.install/sqlitebrowser
