#!/bin/bash

[ -e ~/.install/umake ] && exit

echo "######### Installing umake #########"

sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make
sudo apt-get update
sudo apt-get install ubuntu-make

mkdir -p ~/.install && touch ~/.install/umake
