#!/bin/bash

[ -e ~/.install/vscode ] && exit

echo "######### Installing VS Code #########"

# download from azure if possible, otherwise from Wayback machine
wget --referer 'https://code.visualstudio.com/docs/?dv=linux64_deb' https://az764295.vo.msecnd.net/stable/dea8705087adb1b5e5ae1d9123278e178656186a/code_1.30.1-1545156774_amd64.deb -O vscode.deb || \
wget https://web.archive.org/web/20181230203854/https://az764295.vo.msecnd.net/stable/dea8705087adb1b5e5ae1d9123278e178656186a/code_1.30.1-1545156774_amd64.deb -O vscode.deb

sudo dpkg -i vscode.deb

rm vscode.deb

mkdir -p ~/.install && touch ~/.install/vscode
